export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const CRYPTO_REQUEST_SUCCESS = 'CRYPTO_REQUEST_SUCCESS';
export const CRYPTO_REQUEST_ERROR = 'CRYPTO_REQUEST_ERROR';

export const CRYPTO_PCE_EVOL_REQUEST_SUCCESS =
  'CRYPTO_PCE_EVOL_REQUEST_SUCCESS';
export const CRYPTO_PCE_EVOL_REQUEST_ERROR = 'CRYPTO_PCE_EVOL_REQUEST_ERROR';
